### ISSUE TITLE
Any interest in testing Shoki?

### ISSUE THREAD

**Issue by jnape** [kschuetz/kraftwerk#4]
Hey Kevin,

I was going to start writing some property tests with random sampling for [shoki](http://github.com/palatable/shoki), and I’d like to use this stuff you’ve been working on if you think it’s a good time to start testing it against libraries, or you’re interested in picking up momentum on it.

Any interest in collaborating on that, or would you prefer that I just pick up what you’ve got via fork and run with it locally on my own?

**Comment by kschuetz** [comment]
Hey John,
My library [gauntlet](https://github.com/kschuetz/gauntlet) is intended to be for property-testing, but that one is only 50% done or so.  
[kraftwerk](https://github.com/kschuetz/kraftwerk) is for random data generation only, and aside for some refinement and additional testing, I'd say it is mostly ready to use.  If you want to use this library directly for the data generation part, go for it!   If so, I will continue development on this library and will be open to suggestions.
Kevin

**Comment by kschuetz** [comment]
I'd be happy to help integrate it into shoki.

**Comment by jnape** [comment]
Ah, I didn't realize. I'll create an issue over there then if it's all the same to you and maybe we can chat via the issue.
